# ==============================================================================
# Smart Classroom AI - Frontend Cloud Build Configuration
# Builds and deploys the Vue.js frontend to Cloud Run
# Uses Secret Manager for secure environment variables
# ==============================================================================

steps:
  # Build the Docker image using secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg VITE_API_BASE_URL="$$API_BASE_URL" \
          --build-arg VITE_SUPABASE_URL="$$SUPABASE_URL" \
          --build-arg VITE_SUPABASE_ANON_KEY="$$SUPABASE_ANON_KEY" \
          -t gcr.io/$PROJECT_ID/smart-classroom-frontend:$BUILD_ID \
          -t gcr.io/$PROJECT_ID/smart-classroom-frontend:latest .
    dir: 'Vue-Front'
    secretEnv: ['API_BASE_URL', 'SUPABASE_URL', 'SUPABASE_ANON_KEY']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/smart-classroom-frontend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'smart-classroom-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/smart-classroom-frontend:$BUILD_ID'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'

# Secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/api-base-url/versions/latest
      env: 'API_BASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/supabase-url/versions/latest
      env: 'SUPABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/supabase-anon-key/versions/latest
      env: 'SUPABASE_ANON_KEY'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
